In [1]:
import numpy as np

In [ ]:
1 2 3
4 5 6
7 8 9

A[0,0] A[0,1] A[0,2]
A[1,0] A[1,1] A[1,2]
A[2,0] A[2,2] A[2,2]

In [2]:
a=np.array([1,2,3])

In [4]:
print(a)

[1 2 3]


In [5]:
a.ndim

1

In [6]:
a.size

3

In [7]:
a.nbytes

12

In [8]:
a.itemsize

4

In [9]:
a.dtype

dtype('int32')

In [10]:
a.shape

(3,)

In [11]:
import sys

nums=range(1000)

print(sys.getsizeof(5)*len(nums))

28000


In [14]:
array_nums=np.arange(1000,dtype='int16')
print(array_nums.size * array_nums.itemsize)

2000


In [17]:
import time

SIZE=1000000
l1=range(SIZE)
l2=range(SIZE)

a1=np.arange(SIZE)
a2=np.arange(SIZE)

start=time.time()
[x+y for x,y in zip(l1,l2)]
end=time.time()
print("LIST TOOK:",(end-start)*1000)

start=time.time()
a1+a2
end=time.time()
print("ARRAY TOOK:",(end-start)*1000)



LIST TOOK: 139.46104049682617
ARRAY TOOK: 3.525257110595703


In [18]:
a=np.array([(1,2,3),(4,5,6)])

In [22]:
print(a.shape)

(2, 3)


In [23]:
a.ndim

2

In [24]:
a[0,2]

3

In [25]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
a[1,1]

5

In [35]:
a[0:2,1:]

array([[2, 3],
       [5, 6]])

In [36]:
a.max()

6

In [37]:
a.min()

1

In [38]:
a.sum()

21

In [39]:
a.sum(axis=1)

array([ 6, 15])

In [40]:
a.sum(axis=0)

array([5, 7, 9])

In [42]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [43]:
np.std(a)

1.707825127659933

In [44]:
a=np.array([(1,2,3),(4,5,6)])
b=np.array([(1,2,3),(4,5,6)])

In [45]:
a+b

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [46]:
a-b

array([[0, 0, 0],
       [0, 0, 0]])

In [47]:
a/b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [48]:
a.shape

(2, 3)

In [49]:
b.shape

(2, 3)

In [50]:
np.dot(a,b)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [51]:
A=np.array([(1,2,3),(4,5,6),(7,8,9)])
B=np.array([(1,2,3),(4,5,6),(7,8,9)])

In [52]:
A.shape

(3, 3)

In [53]:
B.shape

(3, 3)

In [54]:
np.dot(A,B)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])